// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultPreferences(): Promise<{ [key: string]: any }>

export function GetPreferences(): Promise<{ [key: string]: any }>

export function RestoreDefault(): Promise<{ [key: string]: any }>

export function SetPreferences(arg1: string, arg2: any): Promise<void>

export function SetPreferencesN(arg1: { [key: string]: any }): Promise<void>
