// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultPreferences() {
    return window['go']['storage']['PreferencesStorage']['DefaultPreferences']()
}

export function GetPreferences() {
    return window['go']['storage']['PreferencesStorage']['GetPreferences']()
}

export function RestoreDefault() {
    return window['go']['storage']['PreferencesStorage']['RestoreDefault']()
}

export function SetPreferences(arg1, arg2) {
    return window['go']['storage']['PreferencesStorage']['SetPreferences'](arg1, arg2)
}

export function SetPreferencesN(arg1) {
    return window['go']['storage']['PreferencesStorage']['SetPreferencesN'](arg1)
}
