// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHashField(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['AddHashField'](arg1, arg2, arg3, arg4, arg5);
}

export function AddListItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['AddListItem'](arg1, arg2, arg3, arg4, arg5);
}

export function AddZSetValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['AddZSetValue'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseConnection(arg1) {
  return window['go']['services']['connectionService']['CloseConnection'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['services']['connectionService']['CreateGroup'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['services']['connectionService']['DeleteConnection'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['services']['connectionService']['DeleteGroup'](arg1, arg2);
}

export function DeleteKey(arg1, arg2, arg3) {
  return window['go']['services']['connectionService']['DeleteKey'](arg1, arg2, arg3);
}

export function GetCmdHistory(arg1, arg2) {
  return window['go']['services']['connectionService']['GetCmdHistory'](arg1, arg2);
}

export function GetConnection(arg1) {
  return window['go']['services']['connectionService']['GetConnection'](arg1);
}

export function GetKeyValue(arg1, arg2, arg3) {
  return window['go']['services']['connectionService']['GetKeyValue'](arg1, arg2, arg3);
}

export function ListConnection() {
  return window['go']['services']['connectionService']['ListConnection']();
}

export function OpenConnection(arg1) {
  return window['go']['services']['connectionService']['OpenConnection'](arg1);
}

export function OpenDatabase(arg1, arg2) {
  return window['go']['services']['connectionService']['OpenDatabase'](arg1, arg2);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['services']['connectionService']['RenameGroup'](arg1, arg2);
}

export function RenameKey(arg1, arg2, arg3, arg4) {
  return window['go']['services']['connectionService']['RenameKey'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['services']['connectionService']['SaveConnection'](arg1, arg2);
}

export function SaveSortedConnection(arg1) {
  return window['go']['services']['connectionService']['SaveSortedConnection'](arg1);
}

export function ScanKeys(arg1, arg2, arg3) {
  return window['go']['services']['connectionService']['ScanKeys'](arg1, arg2, arg3);
}

export function ServerInfo(arg1) {
  return window['go']['services']['connectionService']['ServerInfo'](arg1);
}

export function SetHashValue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['connectionService']['SetHashValue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetKeyTTL(arg1, arg2, arg3, arg4) {
  return window['go']['services']['connectionService']['SetKeyTTL'](arg1, arg2, arg3, arg4);
}

export function SetKeyValue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['connectionService']['SetKeyValue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetListItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['SetListItem'](arg1, arg2, arg3, arg4, arg5);
}

export function SetSetItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['SetSetItem'](arg1, arg2, arg3, arg4, arg5);
}

export function Start(arg1) {
  return window['go']['services']['connectionService']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['services']['connectionService']['Stop'](arg1);
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['services']['connectionService']['TestConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateSetItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['connectionService']['UpdateSetItem'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateZSetValue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['connectionService']['UpdateZSetValue'](arg1, arg2, arg3, arg4, arg5, arg6);
}
