// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFontList() {
  return window['go']['services']['preferencesService']['GetFontList']();
}

export function GetPreferences() {
  return window['go']['services']['preferencesService']['GetPreferences']();
}

export function RestorePreferences() {
  return window['go']['services']['preferencesService']['RestorePreferences']();
}

export function SetPreferences(arg1) {
  return window['go']['services']['preferencesService']['SetPreferences'](arg1);
}
