// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetFontList():Promise<types.JSResp>;

export function GetPreferences():Promise<types.JSResp>;

export function RestorePreferences():Promise<types.JSResp>;

export function SetPreferences(arg1:{[key: string]: any}):Promise<types.JSResp>;
